// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzn2sECuYFM-x8ek1vWmdVUlN9xo4lVfs',
    appId: '1:604139701191:web:dd41858652898bf23d4fe2',
    messagingSenderId: '604139701191',
    projectId: 'vip-number-2ba67',
    authDomain: 'vip-number-2ba67.firebaseapp.com',
    storageBucket: 'vip-number-2ba67.appspot.com',
    measurementId: 'G-856VGRCWFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlyeUGbCZ5XK7no_wTc8d57MvW_mHBUJI',
    appId: '1:604139701191:android:182028bcb79e46703d4fe2',
    messagingSenderId: '604139701191',
    projectId: 'vip-number-2ba67',
    storageBucket: 'vip-number-2ba67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91fISWrucsbhqdLZ5kllhBGkpKZWVAeQ',
    appId: '1:604139701191:ios:326f4624ebcc92eb3d4fe2',
    messagingSenderId: '604139701191',
    projectId: 'vip-number-2ba67',
    storageBucket: 'vip-number-2ba67.appspot.com',
    iosClientId:
        '604139701191-6eeoic5p56pm04boof4jadj14eb9nmph.apps.googleusercontent.com',
    iosBundleId: 'com.example.vipNumber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91fISWrucsbhqdLZ5kllhBGkpKZWVAeQ',
    appId: '1:604139701191:ios:326f4624ebcc92eb3d4fe2',
    messagingSenderId: '604139701191',
    projectId: 'vip-number-2ba67',
    storageBucket: 'vip-number-2ba67.appspot.com',
    iosClientId:
        '604139701191-6eeoic5p56pm04boof4jadj14eb9nmph.apps.googleusercontent.com',
    iosBundleId: 'com.example.vipNumber',
  );
}
